import { colors } from "./colors";
import {
  AlignSelfMap,
  AlignItemsMap,
  AlignContentMap,
  JustifyContentMap,
  FontSizeMap,
  FontWeightMap,
  OpacityMap,
  SpacingMap,
  BorderRadiusMap,
  BorderWidthMap,
  BorderStyleMap,
  ZIndexMap,
  TrackingMap,
  LeadingMap,
  TextAlignMap,
  TextAlignVerticalMap,
  WritingDirectionMap,
  TextDecorationStyleMap,
  TextDecorationLineMap,
  OverflowMap,
  TextTransformMap,
} from "./maps";

export const defaultOptions = {
  colors,
  maps: {
    AlignSelfMap,
    AlignItemsMap,
    AlignContentMap,
    JustifyContentMap,
    FontSizeMap,
    FontWeightMap,
    OpacityMap,
    SpacingMap,
    BorderRadiusMap,
    BorderWidthMap,
    BorderStyleMap,
    ZIndexMap,
    TrackingMap,
    LeadingMap,
    TextAlignMap,
    TextAlignVerticalMap,
    WritingDirectionMap,
    TextDecorationStyleMap,
    TextDecorationLineMap,
    OverflowMap,
    TextTransformMap,
  },
};
